name: Build, Test and Analyze

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch: {}

jobs:
  build-test-analyze:
    name: Build, Test and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          # pip install -r requirements.txt

      - name: Run unit tests with Pytest
        run: |
          pytest --maxfail=1 -q \
            --cov=. --cov-report=xml:coverage.xml \
            --junitxml=pytest-junit.xml

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-artifacts
          path: |
            coverage.xml
            pytest-junit.xml

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          args: >
            -Dsonar.projectKey=PabloBocel_mini_pytest_proyecto
            -Dsonar.organization=pablobocel
            -Dsonar.sources=.
            -Dsonar.python.coverage.reportPaths=coverage.xml
